// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { useModel } from '@@/plugin-model'
import React from 'react'

function Loading() {
  return <div />
}
export default function InitialStateProvider(props: any) {
  const appLoaded = React.useRef(false)
  const { loading = false } = useModel('@@initialState') || {}
  React.useEffect(() => {
    if (!loading) {
      appLoaded.current = true
    }
  }, [loading])
  if (loading && !appLoaded.current) {
    return <Loading />
  }
  return props.children
}
