// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_2 from '/Users/zyb/my/ai-assistant/packages/frontend/src/.umi/plugin-initialState/@@initialState'
import model_1 from '/Users/zyb/my/ai-assistant/packages/frontend/src/models/global'

export const models = {
  model_1: { namespace: 'global', model: model_1 },
  model_2: { namespace: '@@initialState', model: model_2 }
} as const
