// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { Modal, message, notification } from 'antd'
import React from 'react'
import { ApplyPluginsType } from 'umi'

import { getPluginManager } from '../core/plugin'

export function rootContainer(rawContainer) {
  const { appConfig: finalAppConfig = {}, ...finalConfigProvider } =
    getPluginManager().applyPlugins({
      key: 'antd',
      type: ApplyPluginsType.modify,
      initialValue: {}
    })

  let container = rawContainer

  return container
}
