// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react'

import { context } from './helmetContext'
import { HelmetProvider } from '/Users/zyb/my/ai-assistant/node_modules/.pnpm/registry.npmmirror.com+@umijs+renderer-react@4.0.64_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container)
}
