// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// Created by Umi Plugin

export interface IConfigFromPluginsJoi {
  verifyCommit?: {
    scope?: string[]
    allowEmoji?: boolean
  }
  run?: {
    globals?: string[]
  }
}
