// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react'

export async function getRoutes() {
  const routes = {
    '1': {
      path: '/',
      redirect: '/ai/chatgpt',
      parentId: '@@/global-layout',
      id: '1'
    },
    '2': { path: '/user', parentId: '@@/global-layout', id: '2' },
    '3': { path: '/user/login', name: 'userLogin', parentId: '2', id: '3' },
    '4': { path: '/ai', parentId: '@@/global-layout', id: '4' },
    '5': { path: '/ai/chatgpt', name: 'chatgpt', parentId: '4', id: '5' },
    '@@/global-layout': { id: '@@/global-layout', path: '/', isLayout: true }
  } as const
  return {
    routes,
    routeComponents: {
      '1': React.lazy(() => import('./EmptyRoute')),
      '2': React.lazy(
        () =>
          import(/* webpackChunkName: "layouts__index" */ '@/layouts/index.tsx')
      ),
      '3': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__login__Login" */ '@/pages/login/Login.tsx'
          )
      ),
      '4': React.lazy(
        () =>
          import(/* webpackChunkName: "layouts__index" */ '@/layouts/index.tsx')
      ),
      '5': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__ai__chatgpt__LayoutIndex" */ '@/pages/ai/chatgpt/LayoutIndex.tsx'
          )
      ),
      '@@/global-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "layouts__index" */ '/Users/zyb/my/ai-assistant/packages/frontend/src/layouts/index.tsx'
          )
      )
    }
  }
}
